### ISSUE TITLE
Can you update doc ? stylelint@15 deprecated process, replaced with customSyntax

### ISSUE THREAD

**Issue by little-buddy** [kristerkari/stylelint-config-react-native-styled-components#149]
Can you update doc ?

**Comment by little-buddy** [comment]
I know you have done a lot for stylelint, but the css libraries related to react-native are too old, and it will be difficult to upgrade. If you are busy and have no time recently, there is no stable running corresponding fixed version can be released a version, because there are always problems according to the latest environment configuration. I was about to give up styled-components😭😭😭

**Comment by kristerkari** [comment]
Sure, I'll update the docs to match the latest syntax.

**Comment by kristerkari** [comment]
done!
